#define ID_FIT_WIDTH                    1190
#define ID_FIT_HEIGHT                   1191
#define ID_FIT_WINDOW                   1192
#define ID_ZOOM_100                     1193
#define ID_ZOOM_200                     1194
#define ID_ZOOM_300                     1195
#define ID_ZOOM_400                     1196
#define ID_ZOOM_50                      1197
#define ID_SHOW_GRID                    1198
#define ID_TOOL_ZOOM_IN                 1199
#define ID_TOOL_ZOOM_OUT                1200
#define ID_TOOL_NONE                    1201
#define ID_TOOL_PAN                     1202
#define ID_STICK_TO_MAIN                1203
#define ID_NEXT_PAGE                    1204
#define ID_PREV_PAGE                    1205
#define ID_FIRST_PAGE                   1206
#define ID_LAST_PAGE                    1207
#define ID_SHOW_GIDELINES               1208
#define IDC_GR_SIZE_SPIN                4004
#define IDC_ZOOM_OUT                    4005
#define IDC_PAN                         4006
#define IDC_ZOOM_IN                     4007
#define IDC_CH_GRID_COLOR_BTN           4008
#define IDC_CH_GIDE_COLOR_BTN           4009
#define IDC_GRID_SIZE_ED                4011
#define IDD_PREVIEW_SETTINGS_DLG        4012
#define IDC_GRID_COLOR_INDICATOR        4014
#define IDC_GIDE_COLOR_INDICATOR        4015
#define IDC_GIDE_NAME                   4016
#define IDC_GRID_LINED                  4017
#define IDC_GRID_DOTTED                 4018
#define IDC_GIDE_SENS                   4019
#define IDC_GIDE_SENS_SPIN              4021
#define IDR_MAINFRAME                   4100
#define IDR_PREVIEW                     4101
#define ID_PREV_OPTIONS                 4102
